// This file was auto-generated by Fern from our API Definition.
import { ContactsClient } from "./api/resources/contacts/client/Client.mjs";
import { HealthClient } from "./api/resources/health/client/Client.mjs";
import { normalizeClientOptionsWithAuth } from "./BaseClient.mjs";
export class InformlyApiClient {
    constructor(options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }
    get health() {
        var _a;
        return ((_a = this._health) !== null && _a !== void 0 ? _a : (this._health = new HealthClient(this._options)));
    }
    get contacts() {
        var _a;
        return ((_a = this._contacts) !== null && _a !== void 0 ? _a : (this._contacts = new ContactsClient(this._options)));
    }
}
