"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.InformlyApiEnvironment = void 0;
exports.InformlyApiEnvironment = {
    Default: "https://api.informly.com/v1",
};
