"use strict";
// This file was auto-generated by Fern from our API Definition.
Object.defineProperty(exports, "__esModule", { value: true });
exports.InformlyEnvironment = void 0;
exports.InformlyEnvironment = {
    Default: "http://localhost:4000/api/v1",
};
