// This file was auto-generated by Fern from our API Definition.
import * as errors from "./index.mjs";
export function handleNonStatusCodeError(error, rawResponse, method, path) {
    switch (error.reason) {
        case "non-json":
            throw new errors.InformlyApiError({
                statusCode: error.statusCode,
                body: error.rawBody,
                rawResponse: rawResponse,
            });
        case "body-is-null":
            throw new errors.InformlyApiError({
                statusCode: error.statusCode,
                rawResponse: rawResponse,
            });
        case "timeout":
            throw new errors.InformlyApiTimeoutError(`Timeout exceeded when calling ${method} ${path}.`);
        case "unknown":
            throw new errors.InformlyApiError({
                message: error.errorMessage,
                rawResponse: rawResponse,
            });
        default:
            throw new errors.InformlyApiError({
                message: "Unknown error",
                rawResponse: rawResponse,
            });
    }
}
